/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerDashboard;
import com.github.britooo.looca.api.group.discos.Volume;
import controller.ControllerLog;
import controller.ControllerSessao;
import informacoes.InformacoesDoSistema;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.TimerTask;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fehig
 */
public class TelaDash extends javax.swing.JFrame {

    // InformacoesDoSistema info;
    private ControllerDashboard dash;
    private ControllerSessao sessao;
    // private TelaLogin telaLogin;
    private List<Volume> volumeLista;
    private Volume volume;
    private Timer timer;
    private ControllerLog logger;

    /**
     * Creates new form TelaHome
     */
    public TelaDash() throws FileNotFoundException {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("src/main/resources/images/icon.png");
        this.setIconImage(icon);
        logger = ControllerLog.getLogAtivo();
        
        dash = new ControllerDashboard();
        sessao = ControllerSessao.getSessaoAtiva();
        lblUsername.setText(sessao.getUsuarioAtivo().getUsername());
        lblCargo.setText(sessao.getUsuarioAtivo().getTipoUsuario());
        volumeLista = sessao.getInfo().getListaVolumes();
        // volumeLista = info.getListaVolumes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnProjetos = new javax.swing.JPanel();
        btnProjeto = new javax.swing.JLabel();
        btnConfig = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAjuda = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelGpu = new javax.swing.JPanel();
        lblGpu = new javax.swing.JLabel();
        lblGpuValue = new javax.swing.JLabel();
        imgHelpGpu = new javax.swing.JLabel();
        lblDadoGpu = new javax.swing.JLabel();
        panelRam = new javax.swing.JPanel();
        lblRam = new javax.swing.JLabel();
        lblRamValue = new javax.swing.JLabel();
        imgHelpRam = new javax.swing.JLabel();
        lblDadoRam = new javax.swing.JLabel();
        panelCpu = new javax.swing.JPanel();
        lblCpu = new javax.swing.JLabel();
        lblCpuValue = new javax.swing.JLabel();
        imgHelpCpu = new javax.swing.JLabel();
        lblDadoCpu = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnStart1 = new javax.swing.JButton();
        lblInfoCpu = new javax.swing.JLabel();
        lblInfoGpu = new javax.swing.JLabel();
        lblInfoRam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imgLogo1 = new javax.swing.JLabel();
        lblBemVindo1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLateral.setBackground(new java.awt.Color(38, 38, 46));

        btnDashboard.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");
        jLabel1.setAlignmentY(0.4F);

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btnProjetos.setBackground(new java.awt.Color(102, 102, 102));

        btnProjeto.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnProjeto.setForeground(new java.awt.Color(204, 204, 204));
        btnProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProjeto.setText("Projetos");
        btnProjeto.setAlignmentY(0.4F);
        btnProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnProjetosLayout = new javax.swing.GroupLayout(btnProjetos);
        btnProjetos.setLayout(btnProjetosLayout);
        btnProjetosLayout.setHorizontalGroup(
            btnProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProjetosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btnProjetosLayout.setVerticalGroup(
            btnProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btnConfig.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Configurações");
        jLabel4.setToolTipText("");
        jLabel4.setAlignmentY(0.4F);

        javax.swing.GroupLayout btnConfigLayout = new javax.swing.GroupLayout(btnConfig);
        btnConfig.setLayout(btnConfigLayout);
        btnConfigLayout.setHorizontalGroup(
            btnConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnConfigLayout.setVerticalGroup(
            btnConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAjuda.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ajuda");
        jLabel5.setAlignmentY(0.4F);

        javax.swing.GroupLayout btnAjudaLayout = new javax.swing.GroupLayout(btnAjuda);
        btnAjuda.setLayout(btnAjudaLayout);
        btnAjudaLayout.setHorizontalGroup(
            btnAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAjudaLayout.setVerticalGroup(
            btnAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userIconX128.png"))); // NOI18N

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(204, 204, 204));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo.setText("Administrador");

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imgUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCargo)
                .addGap(30, 30, 30))
            .addComponent(btnProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCargo)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(menuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 480));

        jPanel2.setBackground(new java.awt.Color(38, 38, 46));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FluidLogoX128.png"))); // NOI18N

        lblBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(204, 204, 204));
        lblBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBemVindo.setText("Bem vindo,");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(204, 204, 204));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel4.setBackground(new java.awt.Color(233, 231, 231));
        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        panelGpu.setBackground(new java.awt.Color(255, 255, 255));
        panelGpu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelGpu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGpu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGpu.setText("GPU");
        panelGpu.add(lblGpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 12, -1, 31));

        lblGpuValue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblGpuValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGpuValue.setText("---");
        panelGpu.add(lblGpuValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 49, 212, 106));

        imgHelpGpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-de-duvidas .png"))); // NOI18N
        imgHelpGpu.setToolTipText("<html>\nA solução gráfica dedicada, GPU, é importante para a pré-visualização dos clipes e da montagem de efeitos, transições e <br> outras ações costuradas ao longo da sua linha do tempo\n</html>\n");
        panelGpu.add(imgHelpGpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 12, -1, -1));

        lblDadoGpu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadoGpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDadoGpu.setText("Estado de uso");
        panelGpu.add(lblDadoGpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 20));

        panelRam.setBackground(new java.awt.Color(255, 255, 255));
        panelRam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelRam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRam.setText("RAM");
        panelRam.add(lblRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 12, -1, -1));

        lblRamValue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRamValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRamValue.setText("---");
        panelRam.add(lblRamValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, 188, 106));

        imgHelpRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-de-duvidas .png"))); // NOI18N
        imgHelpRam.setToolTipText("<html>\nA memória RAM é importante porque é nela que o editor de vídeo armazena os clipes que estão sendo editados.<br>\nVídeos com resoluções maiores e efeitos mais pesados acabam representando arquivos brutos maiores, que ocupam \n<br> mais espaço na memória RAM.\n</html>");
        panelRam.add(imgHelpRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 12, -1, -1));

        lblDadoRam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadoRam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDadoRam.setText("Estado de uso");
        panelRam.add(lblDadoRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 170, 210, 20));

        panelCpu.setBackground(new java.awt.Color(255, 255, 255));
        panelCpu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelCpu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCpu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCpu.setText("CPU");
        panelCpu.add(lblCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 12, -1, 33));

        lblCpuValue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCpuValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpuValue.setText("---");
        panelCpu.add(lblCpuValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 56, 212, 93));

        imgHelpCpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-de-duvidas .png"))); // NOI18N
        imgHelpCpu.setToolTipText("<html>\nQuanto mais núcleos e threads na sua CPU, mais rápida tende a ser a renderização, já que o computador torna-se capaz de dar conta de <br> mais sequências ao mesmo tempo\n</html>");
        panelCpu.add(imgHelpCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 12, -1, -1));

        lblDadoCpu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadoCpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDadoCpu.setText("Estado de uso");
        panelCpu.add(lblDadoCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 20));

        btnStart.setBackground(new java.awt.Color(57, 199, 156));
        btnStart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 51, 51));
        btnStop.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.setText("Stop");
        btnStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnStop.setEnabled(false);
        btnStop.setMaximumSize(new java.awt.Dimension(42, 27));
        btnStop.setMinimumSize(new java.awt.Dimension(42, 27));
        btnStop.setPreferredSize(new java.awt.Dimension(72, 31));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnStart1.setBackground(new java.awt.Color(102, 153, 255));
        btnStart1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnStart1.setForeground(new java.awt.Color(255, 255, 255));
        btnStart1.setText("Exibir Processos");
        btnStart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        lblInfoCpu.setBackground(new java.awt.Color(233, 231, 231));
        lblInfoCpu.setForeground(new java.awt.Color(233, 231, 231));
        lblInfoCpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoCpu.setText("Sua CPU está com a ultilização acima do valor seguro, encerre alguns processos para que você não perca desempenho");
        lblInfoCpu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblInfoGpu.setBackground(new java.awt.Color(233, 231, 231));
        lblInfoGpu.setForeground(new java.awt.Color(233, 231, 231));
        lblInfoGpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoGpu.setText("Sua GPU está muito quente, encerre alguns processos para que seu trabalho não seja prejudicado");
        lblInfoGpu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblInfoRam.setBackground(new java.awt.Color(233, 231, 231));
        lblInfoRam.setForeground(new java.awt.Color(233, 231, 231));
        lblInfoRam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoRam.setText("Sua RAM está com a ultilização acima do valor seguro, encerre alguns processos para que você não perca desempenho");
        lblInfoRam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInfoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoRam, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(panelCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(panelGpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(panelRam, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfoGpu, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGpu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRam, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfoCpu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoGpu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoRam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 800, 480));

        jPanel3.setBackground(new java.awt.Color(38, 38, 46));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imgLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FluidLogoX128.png"))); // NOI18N

        lblBemVindo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBemVindo1.setForeground(new java.awt.Color(204, 204, 204));
        lblBemVindo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBemVindo1.setText("Bem vindo,");

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(204, 204, 204));
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername1.setText("Nome");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imgLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBemVindo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBemVindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProjetoMouseClicked
        TelaProjetos projetos = null;
        try {
            projetos = new TelaProjetos();
        } catch (IOException ex) {
            Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
        }
        projetos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProjetoMouseClicked

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        TelaProcessos telaProcessos = new TelaProcessos();
        telaProcessos.setVisible(true);
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        cancelTimer();
        try {
            logger.gravarDadosLog("INFO", "A captura de dados foi finalizada.");
        } catch (IOException ex) {
            Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);
        try {
            logger.gravarDadosLog("INFO", "A captura de dados foi inicializada.");
        } catch (IOException ex) {
            Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
        }
        startTimer();
    }//GEN-LAST:event_btnStartActionPerformed
    public void cancelTimer() {
        this.timer.cancel();
        System.out.println("Parando de capturar dados.");

    }

    public void startTimer() {
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                Integer quantidadeDisco = sessao.getInfo().getQuantidadeDisco();
                Double porcentagemRAM = sessao.getInfo().getPorcentagemUsoRAM();
                String porcentagemCPU = String.format("%.0f",  sessao.getInfo().getPorcentagemUsoCPU());
                
                Double tempGpu = sessao.getInfo().getTempGpu();
                alerta(tempGpu, porcentagemRAM, sessao.getInfo().getPorcentagemUsoCPU());  
                // List<> volumes = info.getListaVolumes();
                lblCpuValue.setText(porcentagemCPU + "%");
                lblRamValue.setText(String.format("%.0f%%", porcentagemRAM));

                if (tempGpu >= 0) {
                    //lblGpuValue.setText(String.valueOf(tempGpu));
                    lblGpuValue.setText(String.format("%.0fºC", tempGpu));
                } else {
                    lblGpuValue.setText("N/A");
                }

                try {
                    // Chamar função para dar insert no banco
                    dash.insertDados(porcentagemRAM, Double.parseDouble(porcentagemCPU), tempGpu);
                } catch (IOException ex) {
                    Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
                }

                Integer fkHardware = 4;

                for (int i = 0; i < quantidadeDisco; i++) {
                    volume = volumeLista.get(i);
                    try {
                        dash.insertDadosDisco(sessao.getInfo().getPorcentagemDisponivelDisco(volume).doubleValue(), fkHardware);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    fkHardware++;
                }
            }
        };
        this.timer = new Timer();
        System.out.println("Coletando novos dados ...");
        int period = 3000;
        this.timer.schedule(timerTask, 0, period);
    }
    // Define as cores das labels de informações de acordo com os dados coletados
    public void alerta(Double gpu, Double ram, Double cpu) {
        Color background = new Color(233,231,231);
        Color amarelo = new Color(255,215,0);
        Color verde = new Color(34,139,34);
        String alto = "Alto";
        String moderado = "Moderado";
        String baixo = "Baixo";
        if (!(gpu == -1.0)) {
            if (gpu < 70.0) {
                lblDadoGpu.setForeground(verde);
                lblGpuValue.setForeground(verde);
                lblDadoGpu.setText(baixo);
                lblInfoGpu.setForeground(background);
            } else if (gpu < 90.0) {
                lblDadoGpu.setForeground(amarelo);
                lblGpuValue.setForeground(amarelo);
                lblDadoGpu.setText(moderado);
                lblInfoGpu.setForeground(background);
            } else {
                lblDadoGpu.setForeground(Color.red);
                lblGpuValue.setForeground(Color.red);
                lblDadoGpu.setText(alto);
                lblInfoGpu.setForeground(Color.black);
            }
        }
        
        if(ram < 70.0){
            lblDadoRam.setForeground(verde);
            lblRamValue.setForeground(verde);
            lblDadoRam.setText(baixo);
            lblInfoRam.setForeground(background);
        } else if(ram < 90.0){
            lblDadoRam.setForeground(amarelo);
            lblRamValue.setForeground(amarelo);
            lblDadoRam.setText(moderado);
            lblInfoRam.setForeground(background);
        } else {
            lblDadoRam.setForeground(Color.red);
            lblRamValue.setForeground(Color.red);
            lblDadoRam.setText(alto);
            lblInfoRam.setForeground(Color.black);
        }
        
        if(cpu < 70.0){
            lblDadoCpu.setForeground(verde);
            lblCpuValue.setForeground(verde);
            lblDadoCpu.setText(baixo);
            lblInfoCpu.setForeground(background);
        } else if(cpu < 90.0){
            lblDadoCpu.setForeground(amarelo);
            lblCpuValue.setForeground(amarelo);
            lblDadoCpu.setText(moderado);
            lblInfoCpu.setForeground(background);
        } else {
            lblDadoCpu.setForeground(Color.red);
            lblCpuValue.setForeground(Color.red);
            lblDadoCpu.setText(alto);
            lblInfoCpu.setForeground(Color.black);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaDash().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaDash.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAjuda;
    private javax.swing.JPanel btnConfig;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JLabel btnProjeto;
    private javax.swing.JPanel btnProjetos;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel imgHelpCpu;
    private javax.swing.JLabel imgHelpGpu;
    private javax.swing.JLabel imgHelpRam;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgLogo1;
    private javax.swing.JLabel imgUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblBemVindo1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblCpuValue;
    private javax.swing.JLabel lblDadoCpu;
    private javax.swing.JLabel lblDadoGpu;
    private javax.swing.JLabel lblDadoRam;
    private javax.swing.JLabel lblGpu;
    private javax.swing.JLabel lblGpuValue;
    private javax.swing.JLabel lblInfoCpu;
    private javax.swing.JLabel lblInfoGpu;
    private javax.swing.JLabel lblInfoRam;
    private javax.swing.JLabel lblRam;
    private javax.swing.JLabel lblRamValue;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel panelCpu;
    private javax.swing.JPanel panelGpu;
    private javax.swing.JPanel panelRam;
    // End of variables declaration//GEN-END:variables
}
